LessonProject/Models/ViewModels/ContactView.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;


namespace LessonProject.Models.ViewModels
{
    public class ContactView
    {

        public DateTime Time { get; set; }
        public Dictionary<DateTime,string> AllMessages { get; set; }
        [Required(ErrorMessage = "Введите Сообщение")]
        public string Message { get; set; }
     
    }
}

LessonProject/Models/ViewModels/OrderView.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace LessonProject.Models.ViewModels
{
    public class OrderView
    {
        public int ID { get; set; }
        [Required(ErrorMessage = "Введите Ваше Имя")]
        public string Name { get; set; }
         [Required(ErrorMessage = "Введите Ваш Телефон")]
        public string PhoneNumber { get; set; }
        public int StartHour { get; set; }
        public int StopHour { get; set; }

        public IEnumerable<SelectListItem> StartTimeSelectList
        {
            get
            {
                for (int i = 10; i <= 19 ; i++)
                {
                    yield return new SelectListItem
                    {
                        Value = i.ToString(),
                        Text = i.ToString(),
                        Selected = StartHour == i
                    };
                }
            }
        }

        public IEnumerable<SelectListItem> StopTimeSelectList
        {
            get
            {
                for (int i = 11; i <= 23; i++)
                {
                    yield return new SelectListItem
                    {
                        Value = i.ToString(),
                        Text = i.ToString(),
                        Selected = StopHour == i
                    };
                }
            }
        }






    }
}

LessonProject/Areas/Default/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using LessonProject.Model;
using Ninject;
using LessonProject.Models.ViewModels;
using LessonProject.Models;

namespace LessonProject.Areas.Default.Controllers
{
    public class HomeController : DefaultController
    {
        public ActionResult Index(string strControlPage)
        {
            if (strControlPage == null)
            {
                ViewBag.strControlPage = "";
            }
            else
            {
                ViewBag.strControlPage = strControlPage;
            }
            
            return View();
        }

        public ActionResult UserLogin()
        {
            return View(CurrentUser);
        }
        [HttpGet]
        public ActionResult PersonalInfo()
        {
            ViewBag.avatarpath = String.Format("../Content/themes/pics/{0}.jpg", CurrentUser.ID);
            return View(CurrentUser);
        }
        [HttpPost]
        public ActionResult PersonalInfo(string str)
        {
            ViewBag.avatarpath = String.Format("../Content/themes/pics/{0}.jpg", CurrentUser.ID);
            return View(CurrentUser);
        }

        public ActionResult AboutUs()
        {

            return View();
        }
        [HttpGet]
        public ActionResult Graphic()
        {
            int Days = DateTime.DaysInMonth(DateTime.Now.Year, DateTime.Now.Month);
            ViewBag.Days = Days;
            ViewBag.datetime = DateTime.Now;
            return View();
        }
        [HttpPost]
        public ActionResult Graphic(List<string> data)
        {
            //сделаем временную заглушку.
            if (DateTime.Now.Day.ToString() == data[0] && StaticOrder.ID.Count()!=0)
            {
                ViewBag.transportinfo = "в этот день запланированы перевозки, посмотрите отчеты";
                ViewBag.Count = StaticOrder.starttime.Count();
                ViewBag.starttimemas = StaticOrder.starttime;
                ViewBag.stoptimemas = StaticOrder.stoptime;
                ViewBag.datetime = DateTime.Now;
                ViewBag.Days = DateTime.DaysInMonth(DateTime.Now.Year, DateTime.Now.Month);
            }
            else
            {
                string str = String.Format("на {0} число перевозок не запланировано", data[0]);
                ViewBag.transportinfo = str;
                ViewBag.datetime = DateTime.Now;
                ViewBag.Days = DateTime.DaysInMonth(DateTime.Now.Year, DateTime.Now.Month);
            }
            
            
            //ViewBag.abouttransport = str;
            /*
            int Days = DateTime.DaysInMonth(DateTime.Now.Year, DateTime.Now.Month);
            ViewBag.Days = Days;
            ViewBag.datetime = DateTime.Now;
            */
             return View();
        }

        public ActionResult News()
        {
            return View();
        }
        [HttpGet]
        public ActionResult NewOrder() //заказ перевозки новым пользователем
        {
            var newOrderView = new OrderView();
            ViewBag.CurUser = CurrentUser;
            return View(newOrderView);
        }
        [HttpPost]
        public ActionResult NewOrder(OrderView orderview) //заказ перевозки новым пользователем
        {
            if (orderview.StartHour < DateTime.Today.Hour)
            {
                ViewBag.Message = "Ваш заказ не принят, проверьте время заказа";
            }
            else if (orderview.Name != null && orderview.PhoneNumber != null)
            {
                StaticOrder.ID.Add(CurrentUser.ID);
                //StaticOrder.ID.Add(orderview.ID);
                StaticOrder.phonenumber.Add(orderview.PhoneNumber);
                StaticOrder.clientname.Add(orderview.Name);
                var startdate = DateTime.Today;
                startdate = startdate.AddHours((double)orderview.StartHour);
                StaticOrder.starttime.Add(startdate);
                var stopdate = DateTime.Today;
                stopdate = stopdate.AddHours((double)orderview.StopHour);
                StaticOrder.stoptime.Add(stopdate);
                StaticOrder.cost.Add((orderview.StopHour-orderview.StartHour)*260000);
                //StaticOrder.starttime.Add(orderview.StartHour);
                //StaticOrder.stoptime.Add(orderview.StopHour);
                ViewBag.Message = "Ваш заказ принят, свяжитесь с диспетчером для уточнения деталей";
            }
            else
            {
                ViewBag.Message = "Ваш заказ не принят";
            }
            return View(orderview);
        }

        public ActionResult Orders()
        {
            if (StaticOrder.ID.Count != 0)
            {
                ViewBag.ID = StaticOrder.ID;
                ViewBag.Name = StaticOrder.clientname;
                ViewBag.Phonenumber = StaticOrder.phonenumber;
                ViewBag.Starttime = StaticOrder.starttime;
                ViewBag.Stoptime = StaticOrder.stoptime;
                ViewBag.Cost = StaticOrder.cost;
            }
            else
            {
                ViewBag.Message = "Заказы в базе данных отсутствуют";
            }
            
                return View(CurrentUser); //подумать что здесь вернуть
        }

        [HttpGet]
        public ActionResult Contact()
        {
            ViewBag.Newmessages = StaticInfo.contactchat;
            ViewBag.Count = StaticInfo.contactchat.Count;
            return View();
        }
        [HttpPost]
        public ActionResult Contact(List<string> Message)
        {
            StaticInfo.contactchat.Add(DateTime.Now, Message[0]);
            ViewBag.Newmessages = StaticInfo.contactchat;
            ViewBag.Count = StaticInfo.contactchat.Count;

            //Globalstring.Add(ViewBag.Newmessage);
            //cacheforchat.Add(DateTime.Now, contactView.Message);
            //contactView.AllMessages = cacheforchat;
            return View();
        }

        [HttpGet]
        public ActionResult Contactwithdriver()
        {
            ViewBag.Newmessages = StaticInfo.contactchatwithdriver;
            ViewBag.Count = StaticInfo.contactchat.Count;
            return View(CurrentUser);
        }
        [HttpPost]
        public ActionResult Contactwithdriver(List<string> Message)
        {
            StaticInfo.contactchatwithdriver.Add(DateTime.Now, Message[0]);
            ViewBag.Newmessage = StaticInfo.contactchatwithdriver;
            ViewBag.Count = StaticInfo.contactchatwithdriver.Count;
            return View(CurrentUser);
        }
        public ActionResult Report()
        {
            return View();
        }

    }
}

LessonProject/Areas/Default/Controllers/LoginController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using LessonProject.Models.ViewModels;

namespace LessonProject.Areas.Default.Controllers
{
    public class LoginController : DefaultController
    {
        
        [HttpGet]
        public ActionResult Index()
        {
            return View(new LoginView());
        }

        [HttpPost]
        public ActionResult Index(LoginView loginView)
        {
            if (ModelState.IsValid)
            {
                var user = Auth.Login(loginView.Email, loginView.Password, loginView.IsPersistent);
                if (user != null)
                {
                    return RedirectToAction("PersonalInfo", "Home");
                }
                ModelState["Password"].Errors.Add("Пароли не совпадают");
            }
            return View(loginView);
        }

        public ActionResult Logout()
        {
            Auth.LogOut();
            return RedirectToAction("Index", "Home");
        }
    }

}

LessonProject/Areas/Default/Controllers/RoleController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace LessonProject.Areas.Default.Controllers
{
    public class RoleController : DefaultController
    {
        public ActionResult Index()
        {
            var roles = Repository.Roles.ToList();
            return View(roles);
        }
    }
}

LessonProject/Areas/Default/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Drawing.Imaging;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using LessonProject.Model;
using LessonProject.Models.ViewModels;
using LessonProject.Tools;

namespace LessonProject.Areas.Default.Controllers
{
    public class UserController : DefaultController
    {
        public ActionResult Index()
        {
            ViewBag.Role = Repository.Roles.ToList();
            ViewBag.UserRolebag = Repository.UserRoles.ToList();
            var users = Repository.Users.ToList();
            return View(users);
        }

        [HttpGet]
        public ActionResult Register()
        {
            var newUserView = new UserView();
            return View(newUserView);
        }

        [HttpPost]
        public ActionResult Register(UserView userView)
        {
            if (userView.Captcha != (string)Session[CaptchaImage.CaptchaValueKey])
            {
                ModelState.AddModelError("Captcha", "Текст с картинки введен неверно");
            }
            var anyUser = Repository.Users.Any(p => string.Compare(p.Email, userView.Email) == 0);
            if (anyUser)
            {
                ModelState.AddModelError("Email", "Пользователь с таким email уже зарегистрирован");
            }

            if (ModelState.IsValid)
            {
                var user = (User)ModelMapper.Map(userView, typeof(UserView), typeof(User));

                Repository.CreateUser(user);
                return RedirectToAction("Index");
            }
            return View(userView);
        }

        public ActionResult Captcha()
        {
            Session[CaptchaImage.CaptchaValueKey] = new Random(DateTime.Now.Millisecond).Next(1111, 9999).ToString();
            var ci = new CaptchaImage(Session[CaptchaImage.CaptchaValueKey].ToString(), 211, 50, "Arial");

            // Change the response headers to output a JPEG image.
            this.Response.Clear();
            this.Response.ContentType = "image/jpeg";

            // Write the image to the response stream in JPEG format.
            ci.Image.Save(this.Response.OutputStream, ImageFormat.Jpeg);

            // Dispose of the CAPTCHA image object.
            ci.Dispose();
            return null;
        }
    }
}

LessonProject/Areas/Default/Views/Home/AboutUs.cshtml
@{
    ViewBag.Title = "AboutUs";
    Layout = "~/Areas/Default/Views/Shared/_Layout.cshtml";
}

<form action="/AboutUs" class="form-horizontal" method="post" >
    <fieldset>
        <legend>О Компании</legend>
        <div><img src="\Content\themes\pics\dispetcher.jpg" class="logo" width="200" height="150"></div>  
Транспортная Компания "Возилкин" профессионально осуществляет перевозку сборных грузов по городам Беларуси. 
Образованная в Мае 2014 года в Минске, ТК "Возилкин" на сегодняшний день активно развивается и готова предоставить свои услуги в столице Беларуси.

Собственный автопарк, состоящий более чем из 300 автомобилей выполняющих ежедневные рейсы, поэтому доставкасборных грузов для нас не проблема. Мы стараемся предоставить максимальный сервис для грузоотправителей и грузополучателей.


Новые информационные инструменты позволяют сократить временные затраты на отправку, получение и отслеживаниегрузов.

Работая с нами, вы можете оценить преимущества ряда дополнительных услуг: отслеживания движения груза на сайте, упаковку и обрешетка для хрупких товаров, информирование о доставке. 
Мы ценим время и удобство клиентов, поэтому связаться с нашими менеджерами можно по указанным телефонам, электронной почте или ICQ. Мы готовы выполнить любую задачу, транспортные перевозки, доставка сборных грузов, доставка грузов авто, ж/д или авиатранспортом в любую точку России.
Также поможем осуществить грузоперевозки, цены которых вас приятно удивят. Приятным условием станет формирование оптимальных тарифов, удобство расчета ( отправителем, получателем либо третьим лицом). Мы работаем 5 дней в неделю, до последнего клиента, не так как многие другие транспортные компании. При желании, вы можете самостоятельно рассчитать стоимость заказа, подставив свои данные в специальную форму. Многие тысячи клиентов уже оценили преимущества доставок ТК «Возилкин». 
  

    </fieldset>
</form>

LessonProject/Areas/Default/Views/Home/Contact.cshtml
@model LessonProject.Models.ViewModels.ContactView
@{
    ViewBag.Title = "Contact";
    Layout = "~/Areas/Default/Views/Shared/_Layout.cshtml";
}

<fieldset>
 <legend>Связь с диспетчером</legend>

@using (Html.BeginForm("Contact", "Home", FormMethod.Post, new { @class = "form-horizontal" }))
{  
 if (ViewBag.Count != 0)
 {
    foreach (var mess in ViewBag.Newmessages)
    { 
        String str=string.Format("{0} - {1} \n",mess.Key,mess.Value);
     <p>@str</p>
    
    }
 
 }

   <div class="control-group">
   <div class="controls">
                @* агрегируй во вью модел или через форыч как -то просто @Html.TextBox("AllMessages",Model.AllMessages) 
                Model.AllMessagesничего не даст
                кстати попробовал линк запихнуть, все равно не обновил, тут может перепиши меоды попробуй
                убери гет  в контроллере например, пост вроде проходит но с тем же значением 
                *@  
   </div>
  
        <div class="controls">
     @Html.ValidationMessage("Message")
     <span>@Html.TextBox("Message")</span>
   </div>
   </div>
    <br>
        <div class="form-actions">
            <button type="submit" class="btn btn-primary">
                Отправить
            </button>
        </div>
    
    
}
<br>
<div class="row">
 <div class="col-md-2"><label>Связаться с водителем:</label><br><script type="text/javascript" src="http://www.skypeassets.com/i/scom/js/skype-uri.js"></script>
  <div id="SkypeButton_Call_Driver_1">
   <script type="text/javascript">
      Skype.ui({
          "name": "call",
          "element": "SkypeButton_Call_Driver_1",
          "participants": ["Driver"],
          "imageSize": 32
      });</script>    
  </div>

 </div>
<div class="col-md-6"><label>Связаться с диспетчером:</label><br> <script type="text/javascript" src="http://www.skypeassets.com/i/scom/js/skype-uri.js"></script>
  <div id="SkypeButton_Call_Dispetcher_1">
  <script type="text/javascript">
      Skype.ui({
          "name": "call",
          "element": "SkypeButton_Call_Dispetcher_1",
          "participants": ["Dispetcher"],
          "imageSize": 32
      });</script>
  </div>

</div>
</div>



   
    





</fieldset>

LessonProject/Areas/Default/Views/Home/Contactwithdriver.cshtml
@{
    ViewBag.Title = "Contactwithdriver";
    Layout = "~/Areas/Default/Views/Shared/_Layout.cshtml";
}

<fieldset>
        <legend>Связь с водителем</legend>

@using (Html.BeginForm("Contactwithdriver", "Home", FormMethod.Post, new { @class = "form-horizontal" }))
{
 if (ViewBag.Count != 0)
 {
    foreach (var mess in ViewBag.Newmessages)
    { 
        String str=string.Format("{0} - {1} \n",mess.Key,mess.Value);
     <label>@str</label><div></div>
    
    }
 
 }

   <div class="control-group">
   <div class="controls">

   </div>
   <div class="controls">
     @Html.ValidationMessage("Message")
     <span>@Html.TextBox("Message")</span>
   </div>
   </div>
        <div class="form-actions">
            <button type="submit" class="btn btn-primary">
                Отправить
            </button>
        </div>
    }

</fieldset>

LessonProject/Areas/Default/Views/Home/Graphic.cshtml
@{
    ViewBag.Title = "Graphic";
    Layout = "~/Areas/Default/Views/Shared/_Layout.cshtml";
}
 <fieldset>
        <legend>График перевозок в текущем месяце</legend>
    <label class="control-label" for="time">@ViewBag.datetime</label>
    <div></div>
@if (ViewBag.transportinfo != null)
{ 
    <label class="control-label" for="info">@ViewBag.transportinfo</label>
}
@if (ViewBag.starttimemas != null)
    
{
    <br>
       
    for (int i = 0; i < ViewBag.Count; i++)
    {
        string str = string.Format("перевозка запланирована с {0} по {1}", ViewBag.starttimemas[i], ViewBag.stoptimemas[i]);
         <label class="control-label" for="info">@str</label>  
    }
    
}

<fieldset>
<div class="form-actions">

@using (Html.BeginForm("Graphic", "Home", FormMethod.Post))
{    
 for(int number=1;number<=ViewBag.Days;number++)
 {
     float amount_in_line = number;
    if(number<10)
    {
     string str=string.Format(" "+"{0}" + " ",number);   
     <button type="submit" class="btn btn-primary" name="data" value="@str">
     @str
     </button>
    }
    else
    {
     string str = string.Format("{0}", number);
     ViewBag.str = str;
    <button type="submit" class="btn btn-primary" name="data" value="@str">
      @str
     </button>
    }
     if(amount_in_line%7==0 && amount_in_line!=0)
     {
      <div class="item"> </div>
     }
 }
}
</div>
</fieldset>
</fieldset>

LessonProject/Areas/Default/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Главная страница";
    Layout = "~/Areas/Default/Views/Shared/_Layout.cshtml";
}
@model IList<LessonProject.Model.User>
<html>
    <head>
        <title>@ViewBag.Title</title>
         <link href="@Url.Content("~/Content/Site.css")" rel="stylesheet" type="text/css" />
         <script src="@Url.Content("~/Scripts/jquery-1.7.1.min.js")" type="text/javascript"></script>
         <script src="@Url.Content("~/Scripts/raphael.js")" type="text/javascript"></script>
         <script src="@Url.Content("~/Scripts/ourscript.js")" type="text/javascript"></script>

  <style>
              
    #canvas_container {
    width: 500px;
    border: 1px solid #aaa;
    }

    #slider {
      overflow: hidden;
      position: relative;
      width: 550px;
      border: 2px solid black;
      border-radius: 20px;
      height: 150px;
    }
    #images {
      width: 5000px;
      list-style: none;
      padding: 0;
    }
    #images li {
      float: left;
    }
    #arrow-left{
      top: 55px;
      left: 10px;
    }
    #arrow-right {
      top: 55px;
      right: 10px;
    }
    .arrow {
      cursor: pointer;
      text-align: center;
      padding-top: 12px;
      position: absolute;
      background-color: #aaa;
      border-radius: 10px;
      width: 25px;
      height: 30px;
    }
    .arrow:hover {
    }
  </style>
    
    </head>
<body>

    <fieldset>
        <legend>Добро пожаловать в Программное средство диспетчеризации перевозок</legend>
        <label>Вы можете просмотреть информацию о компании и новости компании</label><div></div>
        <label>Для получения дополнительных возможностей программного средства пожалуйста зарегистрируйтесь!</label>
   
    </fieldset>
    <div id='slider'>
    <div id='arrow-left' class='arrow' style='opacity: 0.1'>&#60;</div>
     <ul id="images" style="margin-left: 15px">
      <li><img src="../Content/themes/pics/karusel1.jpg" height="200" width="200"></li>
      <li><img src="../Content/themes/pics/karusel2.jpg" height="200" width="200"></li>
      <li><img src="../Content/themes/pics/karusel3.jpg" height="200" width="200"></li>
      <li><img src="../Content/themes/pics/karusel4.jpg" height="200" width="200"></li>
      <li><img src="../Content/themes/pics/karusel5.jpg" height="200" width="200"></li>
      <li><img src="../Content/themes/pics/karusel1.jpg" height="200" width="200"></li>
      <li><img src="../Content/themes/pics/karusel2.jpg" height="200" width="200"></li>
      <li><img src="../Content/themes/pics/karusel3.jpg" height="200" width="200"></li>
      <li><img src="../Content/themes/pics/karusel4.jpg" height="200" width="200"></li>
    </ul>
    <div id='arrow-right' class='arrow' style='opacity: 0.1'>&#62;</div>
  </div>


<script>

    var arrowLeft = document.getElementById('arrow-left');
    var arrowRight = document.getElementById('arrow-right');
    var slider = document.getElementById('slider');
    var list = document.getElementById('images');
    var lis = list.getElementsByTagName('li');
    var count = 0;

    slider.onmouseover = function () {
        arrowLeft.style.opacity = '1.0';
        arrowRight.style.opacity = '1.0';
    }
    slider.onmouseout = function () {
        arrowLeft.style.opacity = '0.1';
        arrowRight.style.opacity = '0.1';
    }


    arrowRight.onclick = function () {
        if (count < 6) {
            var value = parseInt(list.style.marginLeft);
            list.style.marginLeft = value - 132 + 'px';
            count++;
        }
    }
    arrowLeft.onclick = function () {
        if (count > 0) {
            var value = parseInt(list.style.marginLeft);
            list.style.marginLeft = value + 132 + 'px';
            count--;
        }
    }

</script>
<div id="canvas_container"></div>
<!-- Первая попытка использования рафаеля
<script type="text/javascript">

    function createCircle() {
        var paper = Raphael("diii", 320, 200);
        var circle = paper.circle(50, 40, 10);
        circle.attr("fill", "#f00");
        circle.attr("stroke", "#fff");
    }

</script>
-->
</body>
</html>

LessonProject/Areas/Default/Views/Home/UserLogin.cshtml
@model LessonProject.Model.User
<html>
<head>
    <title></title>
</head>
    <body>
<header>
 <div class="row">
  <div class="col-md-4"></div>
  <div class="col-md-4"><img src="\Content\themes\pics\logo.png" width="500" height="100"></div>
 </div>   
<br>
     <div class="page">
      <div id="header">
       <div id="menucontainer">
         
@if (Model==null)
{
<!-- видимость незарегистрированного пользователя -->
    
           <ul id="menu"> 
            <li>@Html.ActionLink("Вход", "Index", "Login")</li>
            <li>@Html.ActionLink("Регистрация", "Register", "User")</li>
            <li>@Html.ActionLink("О Компании","AboutUs","Home")</li>
            <li>@Html.ActionLink("Новости","News","Home")</li> 
           </ul>
}

else if(Model.ID<=2) 
{
<!-- Видимость администратора -->   
        <ul id="menu">
          <li>@Html.ActionLink(@Model.Email,"PersonalInfo","Home")</li>
          <li>@Html.ActionLink("Выход", "Logout", "Login")</li>
          <li>@Html.ActionLink("О Компании","AboutUs","Home")</li>
          <li>@Html.ActionLink("Новости","News","Home")</li>  
        </ul>

        <ul id="rubric">
          <li>@Html.ActionLink("Заказать Перевозку","NewOrder","Home")</li>
          <li>@Html.ActionLink("Связь с диспетчером","Contact","Home")</li>
          @*<li>@Html.ActionLink("Просмотр Отчетов","Report","Home")</li>*@
          <li>@Html.ActionLink("График перевозок","Graphic","Home")</li>
          <li><a href="@Url.Action("Index", "Role", new { id = "1" })">Роли</a></li>
          <li>@Html.ActionLink("Пользователи",  "Index", "User")</li>
          <li>@Html.ActionLink("Просмотр перевозок","Orders","Home")</li>
        </ul>
}
else if (Model.ID == 3)
{ 
<!-- Видимость диспетчера -->
         <ul id="menu">
          <li>@Html.ActionLink(@Model.Email,"UserLogin","Home")</li>
          <li>@Html.ActionLink("Выход", "Logout", "Login")</li>
          <li>@Html.ActionLink("О Компании","AboutUs","Home")</li>
          <li>@Html.ActionLink("Новости","News","Home")</li> 
         </ul>
    
         <ul id="rubric">
          <li>@Html.ActionLink("Связь с диспетчером","Contact","Home")</li>
          <li>@Html.ActionLink("График перевозок","Graphic","Home")</li>
          <li>@Html.ActionLink("Текущие перевозки","Orders","Home")</li>
          <li>@Html.ActionLink("Просмотр перевозок","Orders","Home")</li>
         </ul>
         
} 
else if (Model.ID == 4)
{ 
<!-- Видимость водителя -->
         <ul id="menu">
          <li>@Html.ActionLink(@Model.Email,"UserLogin","Home")</li>
          <li>@Html.ActionLink("Выход", "Logout", "Login")</li>
          <li>@Html.ActionLink("О Компании","AboutUs","Home")</li>
          <li>@Html.ActionLink("Новости","News","Home")</li> 
         </ul>
    
         <ul id="rubric">
          <li>@Html.ActionLink("Связь с диспетчером","Contactwithdriver","Home")</li>
          <li>@Html.ActionLink("Просмотр перевозок","Orders","Home")</li>
         </ul>
} 
else if (Model.ID == 5)
{ 
<!-- Видимость директора -->
         <ul id="menu">
          <li>@Html.ActionLink(@Model.Email,"UserLogin","Home")</li>
          <li>@Html.ActionLink("Выход", "Logout", "Login")</li>
          <li>@Html.ActionLink("О Компании","AboutUs","Home")</li>
          <li>@Html.ActionLink("Новости","News","Home")</li> 
         </ul>
    
         <ul id="rubric">
          <li>@Html.ActionLink("Связь с диспетчером","Contact","Home")</li>
          <li>@Html.ActionLink("Просмотр Отчетов","Report","Home")</li>
          <li>@Html.ActionLink("Просмотр перевозок","Orders","Home")</li>
         </ul>
    
} 
else if (Model.ID >= 6)
{ 
<!-- Видимость зарегистрированного пользователя -->
         <ul id="menu">
          <li>@Html.ActionLink(@Model.Email,"UserLogin","Home")</li>
          <li>@Html.ActionLink("Выход", "Logout", "Login")</li>
          <li>@Html.ActionLink("О Компании","AboutUs","Home")</li>
          <li>@Html.ActionLink("Новости","News","Home")</li> 
         </ul>
    
         <ul id="rubric">
          <li>@Html.ActionLink("Связь с диспетчером","Contact","Home")</li>
          @if(ViewBag.contractcount==null)
          {     
          <li>@Html.ActionLink("Заказать Перевозку","NewOrder","Home")</li>
          }
          else
          {
          <li>@Html.ActionLink("Информация о заказе","Orders","Home")</li>
          }
         </ul>
    
} 
       </div>
      </div>
     </div>
</header>
</body>
</html>